### ISSUE TITLE
start.pyw never loads

### ISSUE THREAD

**Issue by docilesmile** [PetitTournesol/Edgeware#27]
Unsure what is actually going wrong but; clean install of Python both manually and via the _EdgewareSetup.bat_ - I get a brief window pop up but then instantly closes, too quick to see what it is. I also get the same if I try to run _Start.pyw_

I've used the DebugScript.bat and for option 1, it seems to indicate the following:

```
"Traceback (most recent call last):
  File "E:\Desktop\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 341, in <module>
    WEB_DICT = json.loads(webF.read())
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 354, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 12 column 39 (char 624)
Done.
Press any key to continue . . ."
```

Weirdly, if I choose option 2 from the DebugScript.bat, it returns the same error:

```
"Running popup.pyw...
Traceback (most recent call last):
  File "E:\Desktop\Edgeware-main\Edgeware-main\EdgeWare\popup.pyw", line 163, in <module>
    web_dict = json.loads(web_file.read())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 354, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 12 column 39 (char 624)
Done.
Press any key to continue . . ."
```

Currently on Win11, Python version 3.11 (having already tried version 3.10 via the automatic install). Have tried running Python as admin, copying and pasting in various 'fixes' for the "invalid control character" issue, but no joy! 

Any suggestions for this absolute Python newb would be very gratefully received!

Thank you :)

**Comment by Test63284** [comment]
I am having the same problem, did you ever find a solution?

edit, figured out how to dodge this issue.
instead of putting a compressed file into the edgeware folder, rename the folder for the package to "resource" and place that into the edgeware folder

**Comment by Sassy0P** [comment]
It seems to me that your web.json is miss-configured, typo or other. 
But I'll try to check. It would be more user friendly for it to not crash

> ```
> "Running popup.pyw...
> Traceback (most recent call last):
>   File "E:\Desktop\Edgeware-main\Edgeware-main\EdgeWare\popup.pyw", line 163, in <module>
>     web_dict = json.loads(web_file.read())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 338, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\capta\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 354, in raw_decode
>     obj, end = self.scan_once(s, idx)
>                ^^^^^^^^^^^^^^^^^^^^^^
> json.decoder.JSONDecodeError: Invalid control character at: line 12 column 39 (char 624)
> Done.
> Press any key to continue . . ."
> ```
