### ISSUE TITLE
Nothing Happens After Save & Exit

### ISSUE THREAD

**Issue by femnitality** [PetitTournesol/Edgeware#50]
Apparently after importing the resource and saving as well as exiting, the program runs with  several command boxes appearing and disappearing as well as the change of the wallpaper on Windows, but other than that, nothing happens. No pop ups, etc. Even though I've cranked it up to 100.

**Comment by Sassy0P** [comment]
Could you share your logs and the output if you try to run it via the debug script?

Your python version could also help

**Comment by femnitality** [comment]
Which feature would you like to run?
1: Start.pyw (Edgeware)
2: Popup.pyw (Popup only)
2a: Popup.pyw (Video only)
3: Config.pyw (Config)
Select number:1
Running start.pyw...
{'default': 'wallpaper.png'}
C:\Users\femni\AppData\Local\Temp\7768-10253-27999-8518.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Edgeware.lnk".

C:\Users\femni\AppData\Local\Temp\7768-10253-27999-8518.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Config.lnk".

C:\Users\femni\AppData\Local\Temp\7768-10253-27999-8518.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Panic.lnk".

href_core=https://blacked.booru.org/index.php
time left: 28139secs
https://blacked.booru.org/index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc
time left: 28138secs
time left: 28137secs
time left: 28136secs
time left: 28135secs
time left: 28134secs
Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blacked.booru.org', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 814, in <module>
    main()
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 488, in main
    booru_downloader:BooruDownloader = BooruDownloader(settings.get('booruName'), settings.get('tagList').split('>'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 549, in __init__
    self.max_page       = int(self.get_page_count())
                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 613, in get_page_count
    self._html = requests.get(self._home_url).text
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blacked.booru.org', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)")))

**Comment by femnitality** [comment]
Which feature would you like to run?
1: Start.pyw (Edgeware)
2: Popup.pyw (Popup only)
2a: Popup.pyw (Video only)
3: Config.pyw (Config)
Select number:1
Running start.pyw...
{'default': 'wallpaper.png'}
C:\Users\femni\AppData\Local\Temp\8536-12993-31776-27300.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Edgeware.lnk".

C:\Users\femni\AppData\Local\Temp\8536-12993-31776-27300.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Config.lnk".

C:\Users\femni\AppData\Local\Temp\8536-12993-31776-27300.vbs(7, 1) WshShortcut.Save: Unable to save shortcut "C:\Users\femni\Desktop\Panic.lnk".

href_core=https://blacked.booru.org/index.php
https://blacked.booru.org/index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc
time left: 27904secs
time left: 27903secs
Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blacked.booru.org', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 814, in <module>
    main()
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 488, in main
    booru_downloader:BooruDownloader = BooruDownloader(settings.get('booruName'), settings.get('tagList').split('>'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 549, in __init__
    self.max_page       = int(self.get_page_count())
                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\Downloads\Edgeware-main\Edgeware-main\EdgeWare\start.pyw", line 613, in get_page_count
    self._html = requests.get(self._home_url).text
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\femni\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blacked.booru.org', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=all+blacked+yiff+furry+rape+gore+gay+yaoi+yuri+bnwo+cnc (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'blacked.booru.org'. (_ssl.c:1002)")))
time left: 27902secs

**Comment by femnitality** [comment]
My python version is the latest one in the website.

**Comment by Sassy0P** [comment]
I can see 2 errors:
1. Edgeware seems to fail at creating the shortcuts. Without more indication. I'll try to check on that.
2. It seems like there a problem with blacked.booru.org ssl(https) certificate. But now I can connect to it. So either they fixed it, or a deeper problem is lurking(python built without ssl support, problem with the url,requests). I'll check on it

**Comment by femnitality** [comment]
Thanks! Hope you can reply to this with some fixes or tips maybe to make it work.

**Comment by ErensDemons** [comment]
Same here, nothing happens, i have the Edgeware icon and my background changes but thats all.

**Comment by Sassy0P** [comment]
Does the problem still occur if disable the booru downloader?

The window say that it is buggy, so it might be way. I'm currently looking on it.

Apparently using deprecated function, maybe juste solving that issue would make it works.

**Comment by ErensDemons** [comment]
> 

it is disabled. i also get the edware icon at the bottom right, but nothing happens. black cmd screens pop up for 0,2 seconds. and thats all sadly

**Comment by Sassy0P** [comment]
> > 
> 
> it is disabled. i also get the edware icon at the bottom right, but nothing happens. black cmd screens pop up for 0,2 seconds. and thats all sadly

Could you also give your log and the output of the debug script ?

**Comment by ErensDemons** [comment]
> > > 
> > 
> > 
> > it is disabled. i also get the edware icon at the bottom right, but nothing happens. black cmd screens pop up for 0,2 seconds. and thats all sadly
> 
> Could you also give your log and the output of the debug script ?

how can i do that? wich log do you need and output?. can you please tell me how i can give you the info you need? =)

in the log folder i did find that one:

CRITICAL:failed to start popup
module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by ErensDemons** [comment]
i fixed it ! with
pip install Pillow==9.5.0
pyt -m pip install olefile


Thank one of your old posts btw !

**Comment by Sassy0P** [comment]
> i fixed it ! with pip install Pillow==9.5.0 pyt -m pip install olefile
> 
> Thank one of your old posts btw !
> 
> the only problem i have now is that theres no sound

It might due to how the multi-threading is managed. I've a version I'm working on, but I need to merge the new fixes into it
